#!/usr/bin/env python3
"""Plot temperature and disk usage trends from daily_overview.csv."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--daily-overview",
        required=True,
        help="Path to daily_overview.csv generated by analyze_summaries.py",
    )
    parser.add_argument("--out-dir", default="./plots", help="Directory for output plot files")
    parser.add_argument("--dpi", type=int, default=180, help="PNG resolution")
    return parser.parse_args()


def _plot_metric(df: pd.DataFrame, metric: str, ylabel: str, title: str, out_path: Path, dpi: int) -> None:
    fig, ax = plt.subplots(figsize=(11, 5.5))

    for pi_name, group in df.groupby("pi"):
        data = group.sort_values("date")
        if metric not in data.columns:
            continue

        values = pd.to_numeric(data[metric], errors="coerce")
        mask = values.notna()
        if not mask.any():
            continue

        ax.plot(
            data.loc[mask, "date"],
            values.loc[mask],
            marker="o",
            linewidth=1.8,
            markersize=3.5,
            label=pi_name,
        )

    ax.set_title(title)
    ax.set_xlabel("Date")
    ax.set_ylabel(ylabel)
    ax.grid(True, linestyle="--", linewidth=0.6, alpha=0.45)
    ax.legend(title="Pi", loc="best")
    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi)
    plt.close(fig)


def main() -> int:
    args = parse_args()
    csv_path = Path(args.daily_overview).resolve()
    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if not csv_path.exists():
        raise SystemExit(f"daily_overview CSV not found: {csv_path}")

    df = pd.read_csv(csv_path)
    if "date" not in df.columns or "pi" not in df.columns:
        raise SystemExit("CSV must include at least 'date' and 'pi' columns")

    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["date", "pi"]).copy()

    temp_plot = out_dir / "temperature_max_c_by_pi.png"
    disk_plot = out_dir / "disk_usage_pct_max_by_pi.png"

    _plot_metric(
        df,
        metric="temp_max_c",
        ylabel="Temperature max (C)",
        title="Daily Maximum Temperature by Pi",
        out_path=temp_plot,
        dpi=args.dpi,
    )

    _plot_metric(
        df,
        metric="disk_pct_max",
        ylabel="Disk usage max (%)",
        title="Daily Maximum Disk Usage by Pi",
        out_path=disk_plot,
        dpi=args.dpi,
    )

    print(f"[INFO] Wrote: {temp_plot}")
    print(f"[INFO] Wrote: {disk_plot}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
